server:
  port: 7003


#EURka配置
eureka:
  instance:
    hostname: eureka7003.com  #Eureka  配置
  client:
    register-with-eureka: false  #表示是否向eureka注册自己
    fetch-registry: false  #若为false 表示自己为注册中心
    service-url: #监控页面
      #单机 ttp://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
